Labor hours redux
DSACMS/repo-scaffolder pull request #157
Opened 2024-10-01 21:15 UTC by IsaacMilarky

## Calculate Labor Hours Using boyter/scc if the tool is installed on the user's computer

## Problem

Labor hours as reported in code.json is difficult for people to know. 

## Solution

Use Scc to provide a good default value for people to use

## Result
Add a post_gen script that checks if https://github.com/boyter/scc is installed. If it is then it uses the labor hours calculation. If it is not installed then it uses a default value of 0. 

This assumes that we are in the .git directory of the project.

## Test Plan

Test manually

2024-10-01 21:50 UTC, natalialuzuriaga requested changes
Tested this and it works accordingly! Some changes needed for the output and project cleanup.

With this, should we remove asking about `laborHours` from the cookiecutter prompts? https://github.com/DSACMS/repo-scaffolder/blob/dev/tier4/%7B%7Bcookiecutter.project_slug%7D%7D/.github/cookiecutter.json#L40

2024-10-01 21:50 UTC, natalialuzuriaga commented on tier4/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
> +        dir_name = "repometrics"
Directory name should be updated here for file+folder cleanup. Could you change mentions `repometrics` to `codejson` in this function

2024-10-01 21:50 UTC, natalialuzuriaga commented on tier4/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
> +            return d['estimatedScheduleMonths'] * 730.001
Could we round the number to a whole number or maybe 1 or 2 decimal points? The code.json schema says `laborHours` should be a number but they didn't specify what kind of number...
https://github.com/GSA/code-gov-data/blob/master/schemas/schema-2.0.0.json#L188
<img width="337" alt="Screenshot 2024-10-01 at 2 44 21 PM" src="https://github.com/user-attachments/assets/06c896d5-62ce-43a1-aa1b-2cc595ff6447">

2024-10-01 21:50 UTC, natalialuzuriaga commented on tier4/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
> +            # Update the json with date_information
Revise comment since this is no longer specific to date_information

2024-10-01 22:55 UTC, IsaacMilarky commented
> Tested this and it works accordingly! Some changes needed for the output and project cleanup.
> 
> With this, should we remove asking about `laborHours` from the cookiecutter prompts? https://github.com/DSACMS/repo-scaffolder/blob/dev/tier4/%7B%7Bcookiecutter.project_slug%7D%7D/.github/cookiecutter.json#L40

Yeah It probably makes sense to no longer ask for 'laborHours'. That way the estimate is being generated the same way for all the repos

2024-10-02 15:25 UTC, natalialuzuriaga requested changes
One last nit then we are good to go

2024-10-02 15:25 UTC, natalialuzuriaga commented on tier4/{{cookiecutter.project_slug}}/.github/codejson/hooks/post_gen_project.py
> +        # Define the repometrics directory to remove
Can you rename mentions to `repometrics` in the variables and comments to `codejson`

2024-10-02 15:26 UTC, natalialuzuriaga commented
> > Tested this and it works accordingly! Some changes needed for the output and project cleanup.
> > With this, should we remove asking about `laborHours` from the cookiecutter prompts? https://github.com/DSACMS/repo-scaffolder/blob/dev/tier4/%7B%7Bcookiecutter.project_slug%7D%7D/.github/cookiecutter.json#L40
> 
> Yeah It probably makes sense to no longer ask for 'laborHours'. That way the estimate is being generated the same way for all the repos

Could you do this removal in this PR?

2024-10-02 15:32 UTC, IsaacMilarky commented
> > > Tested this and it works accordingly! Some changes needed for the output and project cleanup.
> > > With this, should we remove asking about `laborHours` from the cookiecutter prompts? https://github.com/DSACMS/repo-scaffolder/blob/dev/tier4/%7B%7Bcookiecutter.project_slug%7D%7D/.github/cookiecutter.json#L40
> > 
> > 
> > Yeah It probably makes sense to no longer ask for 'laborHours'. That way the estimate is being generated the same way for all the repos
> 
> Could you do this removal in this PR?

For sure I just removed the prompts in the cookiecutter.json and code.json prompts.

2024-10-02 15:57 UTC, natalialuzuriaga requested changes
With the removed field, tested it and it works accordingly. One last change then we are good to go

2024-10-02 15:57 UTC, natalialuzuriaga commented on tier1/{{cookiecutter.project_slug}}/.github/codejson/{{cookiecutter.project_name}}/code.json
> -  "laborHours": "{{ cookiecutter.labor_hours }}",
For all tiers, can we keep this line instead and make the value an empty string? If we fully remove this line then it appends laborHours to the bottom of code.json which I don't really love
<img width="453" alt="Screenshot 2024-10-02 at 8 54 45 AM" src="https://github.com/user-attachments/assets/1ad1ea95-e090-4579-bfb6-3a5e78997d87">

2024-10-02 16:19 UTC, natalialuzuriaga requested changes
Works perfectly!! Please update across all tiers then I'll approve

2024-10-02 16:20 UTC, natalialuzuriaga approved these changes
Oops jk just saw you did. LGTM 🚢

2024-10-02 16:20 UTC, IsaacMilarky commented
> Oops jk just saw you did. LGTM 🚢

No worries lol

2024-10-02 16:20 UTC, merged