Tier 2 checklist markdown
DSACMS/repo-scaffolder pull request #178
Opened 2024-10-11 20:44 UTC by NoobNoob06

converted Tier 2 checklist into a markdown document.

2024-10-15 14:15 UTC, IsaacMilarky requested changes
Some minor issues with links but overall amazing work! This PR is ready to merge after the links are fixed in my opinion.

2024-10-15 14:15 UTC, IsaacMilarky commented on tier2/checklist.md
> +This is a review process to approve CMS-developed software to be released open source at [github.cms.gov](github.cms.org).
I think this should link to github.cms.gov instead of github.cms.org since that shows up as a broken link for me.

2024-10-15 14:15 UTC, IsaacMilarky commented on tier2/checklist.md
> +- [ ] Add code.json to repository and sent over a pull request to [code.gov](code.gov)
This link doesn't work for me. I think it should work if you changed it to `https://code.gov` instead of just `code.gov` in the parenthesis.

2024-10-18 17:47 UTC, IsaacMilarky submitted a review, later dismissed

2024-10-18 17:50 UTC, decause-gov submitted a review, later dismissed
LGTM +1 🚢 
(we will add the release guidelines to this after-the-fact)

2024-10-21 18:38 UTC, natalialuzuriaga requested changes
Very minor nitpicks!

2024-10-21 18:38 UTC, natalialuzuriaga commented on tier2/checklist.md
> +1. Add [repolinter.json](https://github.com/DSACMS/repo-scaffolder/blob/main/tier3/%7B%7Bcookiecutter.project_slug%7D%7D/repolinter.json) to the root directory of your project
Please update the link to use the Tier 2 version

2024-10-21 18:38 UTC, natalialuzuriaga commented on tier2/checklist.md
> +1. Add the tier-specific [checks.yml](https://github.com/DSACMS/repo-scaffolder/blob/main/tier3/%7B%7Bcookiecutter.project_slug%7D%7D/.github/workflows/checks.yml) to the .github directory of your pr
Please update the link to use the Tier 2 version

2024-10-21 20:54 UTC, natalialuzuriaga approved these changes
LGTM! Great work 💯

2024-10-21 21:08 UTC, merged